apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ingress.yaml
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "vinayak@gmail.com"
configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=India
      - OPTION_B=Australia
